l=5
b=8
print("area of reactangle is:",l*b)
r=5
print("parameter of circle is:",(2*3.14*r),"\n")

p=1200
t=8.5
r=3.76
print("Simple interest is:",(p*t*r)/100,"\n")

a=5
b=8
c=9
d=6
e=2
print("average is:",(a+b+c+d+e)//5,"\n")


f=60.54
print(f,"fharenhite to celcius is:",(f-32)*5//9,"\n")



x=int(input("enter no 1:"))
z=int(input("enter no 2:"))
print(x==z,"\n")


s=7
d=9
if((s+d)==5):
    print((s+d),"is equal to 5")
elif((s+d)>5):
    print((s+d),"is grater then 5")
else: print((s+d),"is less then 5")

print("\n")


